/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Animated Woman.glb -o src/components/AnimatedWoman.jsx -r public
*/

import { Html, useAnimations, useCursor, useGLTF } from "@react-three/drei";
import { useFrame, useGraph, useThree } from "@react-three/fiber";
import { useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { SkeletonUtils } from "three-stdlib";
import { useGrid } from "../hooks/useGrid";
import { interactingNPCAtom, socket, targetNPCAtom, userAtom } from "./SocketManager";

const MOVEMENT_SPEED = 0.02; // Reduced speed for natural movement

export function AnimatedWoman({
  hairColor = "green",
  topColor = "pink",
  bottomColor = "brown",
  id,
  name,
  chatMessage,
  isNPC,
  ...props
}) {
  const [interactingNPC, setInteractingNPC] = useAtom(interactingNPCAtom);
  const [targetNPC, setTargetNPC] = useAtom(targetNPCAtom);
  const isInteracting = interactingNPC?.id === id;
  const [hovered, setHovered] = useState(false);
  const position = useMemo(() => props.position, []);
  const [path, setPath] = useState();
  const { gridToVector3, vector3ToGrid } = useGrid();

  useEffect(() => {
    if (!props.path) {
      setPath(null);
      return;
    }
    const newPath = props.path.map((gridPosition) => gridToVector3(gridPosition));
    
    // Deep comparison to avoid unnecessary updates
    if (path?.length === newPath.length) {
      const isSame = path.every((pos, i) => pos.distanceTo(newPath[i]) < 0.01);
      if (isSame) return;
    }
    
    setPath(newPath);
  }, [props.path]);

  const group = useRef();
  const { scene, materials, animations } = useGLTF(
    "/models/Animated Woman.glb"
  );
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);

  const { actions } = useAnimations(animations, group);
  const [animation, setAnimation] = useState("CharacterArmature|Idle");
  const threeScene = useThree((state) => state.scene);

  useEffect(() => {
    if (actions[animation]) {
      actions[animation].reset().fadeIn(0.32).play();
    }
    return () => {
      if (actions[animation]) {
        actions[animation].fadeOut(0.32);
      }
    };
  }, [animation, actions]);

  const [user] = useAtom(userAtom);

  useFrame((state) => {
    // Aggressive Stop: If chatting, interacting, or hovered (for easier clicking)
    if (chatMessage || isInteracting || (isNPC && hovered)) {
      if (path?.length > 0) setPath([]); 
      setAnimation("CharacterArmature|Idle");
    } else if (path?.length && group.current.position.distanceTo(path[0]) > 0.1) {
      const direction = group.current.position
        .clone()
        .sub(path[0])
        .normalize()
        .multiplyScalar(MOVEMENT_SPEED);
      group.current.position.sub(direction);
      
      const targetRotation = Math.atan2(
        path[0].x - group.current.position.x,
        path[0].z - group.current.position.z
      );
      group.current.rotation.y = THREE.MathUtils.lerp(
        group.current.rotation.y,
        targetRotation,
        0.1
      );

      setAnimation("CharacterArmature|Walk");
    } else if (path?.length) {
      path.shift();
    } else {
      setAnimation("CharacterArmature|Idle");
    }

    // Facing logic if talking/interacting
    if ((chatMessage || isInteracting) && (!path?.length || path.length === 0)) {
      const scene = state.scene;
      let targetElement = null;
      
      if (isInteracting) {
        targetElement = scene.getObjectByName(`character-${user}`);
      } else {
        let minDistance = 8;
        scene.traverse((child) => {
          if (child.name.startsWith("character-") && child.name !== `character-${id}`) {
            const dist = group.current.position.distanceTo(child.position);
            if (dist < minDistance) {
              minDistance = dist;
              targetElement = child;
            }
          }
        });
      }

      if (targetElement) {
        const dx = targetElement.position.x - group.current.position.x;
        const dz = targetElement.position.z - group.current.position.z;
        const targetRotation = Math.atan2(dx, dz);
        
        let currentRot = group.current.rotation.y;
        let diff = targetRotation - (currentRot % (Math.PI * 2));
        
        if (diff > Math.PI) diff -= Math.PI * 2;
        if (diff < -Math.PI) diff += Math.PI * 2;

        group.current.rotation.y = THREE.MathUtils.lerp(
          currentRot,
          currentRot + diff,
          0.2 // Faster turn
        );
      }
    }

    if (isInteracting) {
      // Focus camera on NPC Face
      const targetPos = group.current.position.clone();
      const faceHeight = 1.6;
      const player = scene.getObjectByName(`character-${user}`);
      
      if (player) {
        // Calculate direction from NPC to Player for front-view
        const dir = new THREE.Vector3().subVectors(player.position, targetPos).normalize();
        
        // Offset the camera 2.2 units towards the player at face height
        const idealPosition = new THREE.Vector3(
          targetPos.x + dir.x * 2.2,
          targetPos.y + faceHeight,
          targetPos.z + dir.z * 2.2
        );

        state.camera.position.lerp(idealPosition, 0.1);
        
        // Always look at the NPC's face
        const focusPoint = new THREE.Vector3(targetPos.x, targetPos.y + faceHeight, targetPos.z);
        state.camera.lookAt(focusPoint);
      }
      return; 
    }

    if (id === user) {
      // Logic for the local player
      if (targetNPC) {
        const targetElement = state.scene.getObjectByName(`character-${targetNPC.id}`);
        if (targetElement) {
           const dist = group.current.position.distanceTo(targetElement.position);
           if (dist < 2.0) {
             // Close enough, start interaction
             setInteractingNPC(targetNPC);
             setTargetNPC(null);
             if (path?.length > 0) setPath([]);
           }
        }
      }

      if (!interactingNPC) {
        state.camera.position.x = THREE.MathUtils.lerp(state.camera.position.x, group.current.position.x + 8, 0.05);
        state.camera.position.y = THREE.MathUtils.lerp(state.camera.position.y, group.current.position.y + 8, 0.05);
        state.camera.position.z = THREE.MathUtils.lerp(state.camera.position.z, group.current.position.z + 8, 0.05);
        state.camera.lookAt(group.current.position);
      }
    }
  });

  useCursor(isNPC && hovered && !interactingNPC);

  return (
    <group
      ref={group}
      position={position}
      dispose={null}
      name={`character-${id}`}
      onPointerDown={(e) => {
        if (isNPC && !interactingNPC) {
          e.stopPropagation();
          // Walk to NPC first
          const player = threeScene.getObjectByName(`character-${user}`);
          if (player) {
            socket.emit(
              "move",
              vector3ToGrid(player.position),
              vector3ToGrid(group.current.position)
            );
            setTargetNPC({ id, hairColor, topColor, bottomColor, name });
          }
        }
      }}
      onPointerOver={() => isNPC && setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      {/* Name Tag - Positioned precisely at head level */}
      <Html position={[0, 2.7, 0]} center>
        <div
          style={{
            background: "rgba(0, 0, 0, 0.9)",
            backdropFilter: "blur(12px)",
            padding: "8px 20px",
            borderRadius: "40px",
            color: "white",
            fontSize: "14px",
            fontWeight: "900",
            whiteSpace: "nowrap",
            border: `3px solid ${topColor}`,
            pointerEvents: "none",
            userSelect: "none",
            boxShadow: "0 8px 20px rgba(0,0,0,0.6)",
            textTransform: "uppercase",
            letterSpacing: "1px",
            textAlign: "center",
            opacity: isInteracting ? 0 : 1,
            transition: "opacity 0.3s",
          }}
        >
          {name || "AGENT"}
        </div>
      </Html>

      {/* Chat Bubble - Positioned above the name tag */}
      <Html position={[0, 3.4, 0]} center>
        <div
          style={{
            background: "rgba(255, 255, 255, 0.95)",
            padding: "12px 20px",
            borderRadius: "20px 20px 20px 4px",
            boxShadow: "0 10px 25px rgba(0,0,0,0.3)",
            whiteSpace: "nowrap",
            opacity: chatMessage && !isInteracting ? 1 : 0,
            transform: `scale(${chatMessage && !isInteracting ? 1 : 0.4}) translateY(${chatMessage && !isInteracting ? 0 : 20}px)`,
            transition: "all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
            fontWeight: "bold",
            fontSize: "16px",
            color: "#111",
            border: "2px solid #fff",
            pointerEvents: "none",
            maxWidth: "300px",
            overflow: "hidden",
            textOverflow: "ellipsis"
          }}
        >
          {chatMessage}
          <div style={{
            position: 'absolute',
            bottom: '-12px',
            left: '10%',
            width: '0',
            height: '0',
            borderLeft: '12px solid transparent',
            borderRight: '12px solid transparent',
            borderTop: '12px solid rgba(255, 255, 255, 0.95)',
          }} />
        </div>
      </Html>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <group name="Casual_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Casual_Body_1"
              geometry={nodes.Casual_Body_1.geometry}
              material={materials.White}
              skeleton={nodes.Casual_Body_1.skeleton}
            >
              <meshStandardMaterial color={topColor} />
            </skinnedMesh>
            <skinnedMesh
              name="Casual_Body_2"
              geometry={nodes.Casual_Body_2.geometry}
              material={materials.Skin}
              skeleton={nodes.Casual_Body_2.skeleton}
            />
          </group>
          <group name="Casual_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Casual_Feet_1"
              geometry={nodes.Casual_Feet_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Casual_Feet_1.skeleton}
            />
            <skinnedMesh
              name="Casual_Feet_2"
              geometry={nodes.Casual_Feet_2.geometry}
              material={materials.Grey}
              skeleton={nodes.Casual_Feet_2.skeleton}
            />
          </group>
          <group name="Casual_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Casual_Head_1"
              geometry={nodes.Casual_Head_1.geometry}
              material={materials.Skin}
              skeleton={nodes.Casual_Head_1.skeleton}
            />
            <skinnedMesh
              name="Casual_Head_2"
              geometry={nodes.Casual_Head_2.geometry}
              material={materials.Hair_Blond}
              skeleton={nodes.Casual_Head_2.skeleton}
            >
              <meshStandardMaterial color={hairColor} />
            </skinnedMesh>
            <skinnedMesh
              name="Casual_Head_3"
              geometry={nodes.Casual_Head_3.geometry}
              material={materials.Hair_Brown}
              skeleton={nodes.Casual_Head_3.skeleton}
            />
            <skinnedMesh
              name="Casual_Head_4"
              geometry={nodes.Casual_Head_4.geometry}
              material={materials.Brown}
              skeleton={nodes.Casual_Head_4.skeleton}
            />
          </group>
          <skinnedMesh
            name="Casual_Legs"
            geometry={nodes.Casual_Legs.geometry}
            material={materials.Orange}
            skeleton={nodes.Casual_Legs.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <meshStandardMaterial color={bottomColor} />
          </skinnedMesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Animated Woman.glb");
